---
- name: Copy backend files to web server
  synchronize:
    src: /home/schoolboy/penugasan-camin-2-ajk/Penugasan-2-AJK/roles/backend-build
    dest: /var/www/backend
    delete: yes

- name: Restart backend service
  service:
    name: backend
    state: restarted
