---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Ensure MySQL service is started
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

# Add more tasks for MySQL configuration as needed
