---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Ensure Nginx service is started
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

# Add more tasks for Nginx configuration as needed
